# Generated by Django 6.0.7 on 2026-07-13 03:24

import travel.utils
import travel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hokkaido', 'Hokkaido'), ('tohoku', 'Tohoku'), ('kanto', 'Kanto'), ('chubu', 'Chubu'), ('kansai', 'Kansai'), ('chugoku', 'Chugoku'), ('shikoku', 'Shikoku'), ('kyushu', 'Kyushu'), ('okinawa', 'Okinawa')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=travel.utils.region_image_upload_path, validators=[travel.validators.validate_image_size], verbose_name='Region Image')),
                ('display_order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
