# Generated by Django 6.0.7 on 2026-07-13 06:42

import django.db.models.deletion
import travel.utils
import travel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=travel.utils.prefecture_image_upload_path, validators=[travel.validators.validate_image_size], verbose_name='Prefecture Image')),
                ('display_order', models.PositiveSmallIntegerField(unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefectures', to='travel.region')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
