# Generated by Django 6.0.7 on 2026-07-13 09:44

import django.db.models.deletion
import travel.utils
import travel.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_prefecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=travel.utils.place_image_upload_path, validators=[travel.validators.validate_image_size], verbose_name='Place Image')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('official_website', models.URLField(blank=True)),
                ('travel_tips', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='travel.prefecture')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('prefecture', 'slug'), name='unique_place_slug_per_prefecture')],
            },
        ),
    ]
