# Generated by Django 6.0.7 on 2026-07-14 23:30

import django.db.models.deletion
import travel.utils
import travel.validators
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app, user_model)
    Profile = apps.get_model('travel', 'Profile')

    for user_id in User.objects.values_list('pk', flat=True).iterator():
        Profile.objects.get_or_create(user_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=80)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=travel.utils.profile_image_upload_path, validators=[travel.validators.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            create_profiles_for_existing_users,
            migrations.RunPython.noop,
        ),
    ]
