# Generated by Django 6.0.7 on 2026-07-22 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['status', '-created_at'], name='place_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['prefecture', 'status'], name='place_pref_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', '-created_at'], name='review_place_created_idx'),
        ),
    ]
