# Generated by Django 6.0.7 on 2026-07-23 07:09

import travel.utils
import travel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_place_best_season_place_latitude_place_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=travel.utils.place_image_upload_path, validators=[travel.validators.validate_image_size, travel.validators.validate_image_safety], verbose_name='Place Image'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to=travel.utils.place_gallery_upload_path, validators=[travel.validators.validate_image_size, travel.validators.validate_image_safety]),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=travel.utils.prefecture_image_upload_path, validators=[travel.validators.validate_image_size, travel.validators.validate_image_safety], verbose_name='Prefecture Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=travel.utils.profile_image_upload_path, validators=[travel.validators.validate_image_size, travel.validators.validate_image_safety]),
        ),
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=travel.utils.region_image_upload_path, validators=[travel.validators.validate_image_size, travel.validators.validate_image_safety], verbose_name='Region Image'),
        ),
    ]
