# Generated by Django 6.0.7 on 2026-07-23 07:14

import django.core.validators
import travel.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_place_image_alter_placeimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to=travel.utils.place_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['status', 'best_season'], name='place_status_season_idx'),
        ),
    ]
