# Generated by Django 6.0.7 on 2026-07-24 01:30

import django.core.validators
import django.db.models.deletion
import travel.utils
import travel.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_placeimage_thumbnail_alter_place_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketCounter',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('registered_email', models.EmailField(editable=False, max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('account', 'Account'), ('place_submission', 'Place Submission'), ('review_issue', 'Review Issue'), ('bug_report', 'Bug Report'), ('feature_request', 'Feature Request'), ('report_content', 'Report Content'), ('other', 'Other')], max_length=32)),
                ('subject', models.CharField(max_length=180)),
                ('related_url', models.URLField(blank=True, max_length=500)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=travel.utils.support_screenshot_upload_path, validators=[travel.validators.validate_support_screenshot_size, travel.validators.validate_image_safety])),
                ('message', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting_for_user', 'Waiting for User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=24)),
                ('internal_notes', models.TextField(blank=True)),
                ('deduplication_key', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_administrator', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_status_created_idx'), models.Index(fields=['category', '-created_at'], name='support_category_created_idx'), models.Index(fields=['user', '-created_at'], name='support_user_created_idx')],
            },
        ),
    ]
