# Generated by Django 6.0.7 on 2026-07-24 01:51

import uuid
from django.db import migrations, models
from django.utils import timezone


def trust_and_normalize_existing_accounts(apps, schema_editor):
    """Preserve access for pre-verification users and fail safely on duplicates."""

    User = apps.get_model("auth", "User")
    Profile = apps.get_model("travel", "Profile")
    seen = {}
    verified_at = timezone.now()
    for user in User.objects.order_by("pk"):
        normalized = (user.email or "").strip().lower()
        if normalized:
            duplicate_id = seen.get(normalized)
            if duplicate_id:
                raise RuntimeError(
                    f"Users {duplicate_id} and {user.pk} share the same email ignoring case. "
                    "Resolve this duplicate before applying the migration."
                )
            seen[normalized] = user.pk
        if user.email != normalized:
            User.objects.filter(pk=user.pk).update(email=normalized)
        Profile.objects.update_or_create(
            user_id=user.pk,
            defaults={"email_verified": True, "email_verified_at": verified_at},
        )


def keep_existing_accounts_verified(apps, schema_editor):
    """Verification cannot be safely undone once accounts have used the feature."""


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_supportticketcounter_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            trust_and_normalize_existing_accounts,
            reverse_code=keep_existing_accounts_verified,
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX auth_user_email_ci_unique "
                "ON auth_user (LOWER(email)) WHERE email <> '';"
            ),
            reverse_sql="DROP INDEX IF EXISTS auth_user_email_ci_unique;",
        ),
    ]
