# Generated by Django 6.0.7 on 2026-07-24 05:36

import django.core.validators
import django.db.models.deletion
import travel.utils
import travel.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_contentreport_resolved_by_place_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional replacement for the currently published cover image.', null=True, upload_to=travel.utils.place_revision_image_upload_path, validators=[travel.validators.validate_image_size, travel.validators.validate_image_safety])),
                ('city', models.CharField(blank=True, max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('official_website', models.URLField(blank=True)),
                ('travel_tips', models.TextField(blank=True)),
                ('best_season', models.CharField(choices=[('year_round', 'Year-round'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='year_round', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='travel.place')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_revisions', to='travel.prefecture')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_place_revisions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_place_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PlaceRevisionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=travel.utils.place_revision_gallery_upload_path, validators=[travel.validators.validate_image_size, travel.validators.validate_image_safety])),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to=travel.utils.place_revision_thumbnail_upload_path)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='travel.placerevision')),
            ],
            options={
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='placerevision',
            index=models.Index(fields=['status', '-updated_at'], name='revision_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='placerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('place',), name='unique_pending_revision_per_place'),
        ),
    ]
