import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import { ErrorState, LoadingState } from '../components/AsyncState'
import FormField from '../components/FormField'
import ImageDropInput from '../components/ImageDropInput'
import { useApi } from '../hooks/useApi'

const initial = { name: '', description: '', city: '', google_maps_url: '', official_website: '', travel_tips: '', best_season: 'year_round', latitude: '', longitude: '', prefecture_id: '' }

export default function PlaceFormPage() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const [params] = useSearchParams()
  const { data: prefectures, loading: prefLoading } = useApi('/prefectures/')
  const { data: place, loading: placeLoading, error } = useApi(editing ? `/places/${id}/` : '/health/', [id])
  const [values, setValues] = useState(initial); const [image, setImage] = useState(null); const [galleryFiles, setGalleryFiles] = useState([]); const [errors, setErrors] = useState({}); const [busy, setBusy] = useState(false)
  useEffect(() => { if (editing && place?.id) { const revision = place.latest_revision; const source = revision && ['pending', 'rejected'].includes(revision.status) ? revision : place; setValues({ name: source.name, description: source.description, city: source.city, google_maps_url: source.google_maps_url, official_website: source.official_website, travel_tips: source.travel_tips, best_season: source.best_season, latitude: source.latitude || '', longitude: source.longitude || '', prefecture_id: String(source.prefecture.id) }) } else if (!editing && prefectures) { const selected = prefectures.find((p) => p.name === params.get('prefecture')); setValues((v) => ({ ...v, prefecture_id: String(selected?.id || '') })) } }, [editing, place, prefectures, params])
  if (prefLoading || placeLoading) return <LoadingState />; if (error) return <ErrorState error={error} />
  const change = (e) => setValues((v) => ({ ...v, [e.target.name]: e.target.value }))
  const submit = async (e) => { e.preventDefault(); setBusy(true); setErrors({}); const body = new FormData(); Object.entries(values).forEach(([key, value]) => body.append(key, value)); if (image) body.append('image', image); try { const result = await api(editing ? `/places/${id}/` : '/places/', { method: editing ? 'PATCH' : 'POST', body }); for (const [index, file] of galleryFiles.entries()) { const galleryBody = new FormData(); galleryBody.append('image', file); galleryBody.append('display_order', String(index)); await api(`/places/${result.id}/images/`, { method: 'POST', body: galleryBody }) } navigate(`/places/${result.id}/${result.slug}`) } catch (err) { setErrors(err.fields || { general: err.message }) } finally { setBusy(false) } }
  return <section className="form-page"><div><p className="eyebrow">{editing ? 'Update your contribution' : 'Community contribution'}</p><h1>{editing ? 'Edit place' : 'Suggest a place'}</h1><p>{editing ? place.latest_revision?.status === 'pending' ? 'Update your pending proposal. The approved place stays public until an administrator accepts these changes.' : 'Your proposed changes will be reviewed before they replace the approved place.' : 'Your destination will be reviewed by the Japan 47 team before publication.'}</p></div><form onSubmit={submit} encType="multipart/form-data">{errors.general && <p className="form-error">{errors.general}</p>}
    <FormField label="Prefecture" name="prefecture_id" errors={errors} required><select id="prefecture_id" name="prefecture_id" value={values.prefecture_id} onChange={change} required><option value="">Choose a prefecture</option>{prefectures.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.region.label}</option>)}</select></FormField>
    <FormField label="Place name" name="name" errors={errors} required><input id="name" name="name" value={values.name} onChange={change} maxLength="120" required /></FormField>
    <FormField label="Description" name="description" errors={errors} required><textarea id="description" name="description" value={values.description} onChange={change} rows="7" required /></FormField>
    <FormField label="Best season" name="best_season" errors={errors} required><select id="best_season" name="best_season" value={values.best_season} onChange={change}><option value="year_round">Year-round</option><option value="spring">Spring</option><option value="summer">Summer</option><option value="autumn">Autumn</option><option value="winter">Winter</option></select></FormField>
    <FormField label="Image" name="image" errors={errors} hint="JPEG, PNG, WebP, or HEIF; maximum 8 MB."><ImageDropInput id="image" onFiles={setImage} /></FormField>
    <FormField label="Gallery images" name="gallery_images" errors={errors} hint="Select or drop multiple images to build the place gallery."><ImageDropInput id="gallery_images" multiple onFiles={setGalleryFiles} /></FormField>
    <div className="form-grid">{[['city','City'],['google_maps_url','Google Maps URL'],['official_website','Official website']].map(([name,label]) => <FormField key={name} label={label} name={name} errors={errors}><input id={name} name={name} type={name.includes('url') || name.includes('website') ? 'url' : 'text'} value={values[name]} onChange={change} /></FormField>)}</div>
    <div className="form-grid"><FormField label="Latitude" name="latitude" errors={errors} hint="Optional, between -90 and 90."><input id="latitude" name="latitude" type="number" min="-90" max="90" step="0.000001" value={values.latitude} onChange={change} /></FormField><FormField label="Longitude" name="longitude" errors={errors} hint="Optional, between -180 and 180."><input id="longitude" name="longitude" type="number" min="-180" max="180" step="0.000001" value={values.longitude} onChange={change} /></FormField></div>
    <FormField label="Travel tips" name="travel_tips" errors={errors}><textarea id="travel_tips" name="travel_tips" value={values.travel_tips} onChange={change} rows="4" /></FormField><div className="actions"><button disabled={busy} className="button button--primary">{busy ? 'Saving…' : editing ? place.latest_revision?.status === 'pending' ? 'Update pending changes' : 'Submit changes for review' : 'Submit for review'}</button><Link to={editing ? `/places/${id}/${place.slug}` : '/places'}>Cancel</Link></div>
  </form></section>
}
